### ISSUE TITLE
[Suggestion] Modrinth support

### ISSUE THREAD

**Issue by youmukonpaku1337** [quiqueck/BCLib#6]
### Description

Since this mod does not seem like it cares for money, (enabled 3rd party api), a good idea would be to make this mod available on modrinth, because it's a way better experience there.
First of all, there are no captchas every page reload, no advertisements everywhere (and even if they add them they'll be anonymized), no delay for downloads, no 403 forbidden for wget, better filters, better search, and they're actively working on payouts, and the approval is super fast, it could take less than 5 minutes.

Mods like this block people from moving to modrinth fully, so it would be great to put this mod on modrinth.

**Comment by quiqueck** [comment]
We will discuss this internally.

**Comment by ImUrX** [comment]
Better Nether seems to have disabled 3rd party downloads, so modrinth support would be nice tbh.

**Comment by youmukonpaku1337** [comment]
so uh

**Comment by youmukonpaku1337** [comment]
did you discuss this?

**Comment by quiqueck** [comment]
We are open to publish on Modrinth. But before we do, I need to get some things in place and of course find the time to build the Modrinth pages :)

**Comment by youmukonpaku1337** [comment]
okay

**Comment by PinkGoosik** [comment]
I upvote

**Comment by quiqueck** [comment]
Just a heads-up: I just pushed the first bclib version to Modrinth (https://modrinth.com/mod/bclib). Our other Mods will follow in the next days.

**Comment by PinkGoosik** [comment]
uploading the latest version of the mods for each major minecraft version might be a good idea for an archival purpose plus some people still play 1.18.2

**Comment by quiqueck** [comment]
That is a "complicated" matter for two reasons :)

1. I was not involved in any version that was made before 1.17, so I do not feel comfortable to move those to another platform
2. We do not currently support pre 1.19 Versions (due to time constraints), I am not sure if it sends the wrong Signal If I move those over :)

But I am open to discussion. So far I enjoy the Modrinth experience. Simplifies a lot of things for developers.

**Comment by JulianVennen** [comment]
I don't think that uploading the latest versions of each Minecraft Version makes you responsible for providing support for them.

I work at Aternos (a free Minecraft server host). On our website, users can't upload mod jars directly because that could be abused on our free service. Instead, users can download mods to their server using the mods list on our website, which uses the CurseForge/Modrinth API.
 
Since you disabled project distribution on CurseForge now, it's no longer possible to download your mods on our platform from CurseForge. If you choose not to upload older versions of your mods to Modrinth then our users won't be able to download your mods on these versions.

**Comment by quiqueck** [comment]
I am very sorry. When I disabled the Distribution of CF, I did not think about older Version still being in use and Figured that Modrinth would serve as a replacement.

I just re-enabled the distribution API as a quick fix for now.
