### ISSUE TITLE
[Bug] Weird spam in console from BetterX/BCLib

### ISSUE THREAD

**Issue by itsdinkd** [quiqueck/BCLib#66]
### What happened?

this gets spammed in console talking about making sure terrablender uses settings

https://gist.github.com/itsdinkd/8ab40813f3381d84a065aae02e9f381c

better-end-2.1.2.jar
better-nether-7.1.2.jar

### BCLib

bclib-2.1.5.jar

### Fabric API

.70

### Fabric Loader

14.12

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
You should be able to remove those logs by disabling verbose logging.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/216794825-ccd244a7-131b-49c6-897d-67033be0565e.png)


> You should be able to remove those logs by disabling verbose logging.

**Comment by itsdinkd** [comment]
> You should be able to remove those logs by disabling verbose logging.

btw turned off verbose and it still logs.
![image](https://user-images.githubusercontent.com/35115304/218254192-85b57bdf-a1cf-4eeb-9b44-65a81da715b3.png)
![image](https://user-images.githubusercontent.com/35115304/218254203-ab70ef18-de0b-49f8-8851-71d3d425df68.png)

**Comment by quiqueck** [comment]
Should be fixed in the latest release.

**Comment by itsdinkd** [comment]
I believe you said in discord that it shouldn't iterate over the same dimension infinite times. Is this fine that it's doing that in the background? @quiqueck

**Comment by quiqueck** [comment]
From the log, I do not see an infinite cycle. The message is printed for each individual biome once, which can be a lot of biomes. And the game initialises the data structure that is responsible for the log entry multiple times during world load/creation. So from what I can see here, this is expected behaviour (except that it is not removed when verbose logging is turned off). Please let me know if I am missing something here :)
